version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\Willian Lemos\Documents\Estudo\EBAC\ebacModulos\volumes\postgres:/var/lib/postgresql/data
    networks:
      - nt-postgres


  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "willian@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - nt-postgres

networks:
  nt-postgres:
    driver: bridge